#!/usr/bin/env bash
#be sure to make sript executable with this command. "chmod +x YOURFILENAME.sh"

echo "Place me in the same folder where a file to be encrypted is present."
echo "Enter the Exact File Name with extension"
read -r file

# decryption command
# gpg -d filename.gpg > filename

gpg -c "$file"
echo "I have encrypted the file sucessfully..."
echo "Now I will be removing the original file"
rm -rf "$file"
